# Generated by Django 4.0 on 2021-12-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
